<?php
$posts = json_decode(file_get_contents(__DIR__.'/../data/blog-posts.json'), true) ?: [];
$categories = array_values(array_unique(array_column($posts, 'category')));
function e($value){ return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function trDate($date){ $m=['01'=>'Ocak','02'=>'Şubat','03'=>'Mart','04'=>'Nisan','05'=>'Mayıs','06'=>'Haziran','07'=>'Temmuz','08'=>'Ağustos','09'=>'Eylül','10'=>'Ekim','11'=>'Kasım','12'=>'Aralık']; [$y,$mo,$d]=explode('-',$date); return (int)$d.' '.$m[$mo].' '.$y; }
function categoryClass($category){ return strtolower(str_replace([' ','-','İ','ı'],['-','-','i','i'],$category)); }
?>
<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Blog | Vensis</title><meta name="description" content="Fan, havalandırma, Vortice ve ex-proof sistemler hakkında teknik rehberler ve seçim yazıları."><link rel="canonical" href="https://www.vensisklima.com.tr/blog/"><link rel="stylesheet" href="/assets/blog.css?v=20260721-1"><link rel="icon" type="image/webp" href="/assets/logo-fixed.webp"></head><body>
<div class="site-top"><div class="wrap"><span>Vensis Havalandırma Ltd. Şti.</span><span>0312 945 13 60 · vensis@vensis.com.tr</span></div></div><header class="site-header"><div class="wrap site-nav"><a class="site-logo" href="/"><img src="/assets/logo-fixed.webp" alt="Vensis"></a><nav class="site-menu"><a href="/">Ana Sayfa</a><a href="/#cozumler">Çözümler</a><a href="/#referanslar">Referanslar</a><a class="active" href="/blog/">Blog</a><a href="/#iletisim">İletişim</a></nav><a class="site-btn" href="/#iletisim">Projenizi Konuşalım</a></div></header>
<main><section class="blog-hero"><div class="wrap"><span class="eyebrow">VENSİS BİLGİ MERKEZİ</span><h1>Teknik bilgi,<br>doğru seçim.</h1><p>Altı uzmanlık sitemizde yayımlanan yazıları tek arşivde topladık; tekrar eden içerikleri ayıklayarak daha düzenli bir kaynak oluşturduk.</p></div></section><section class="blog-list"><div class="wrap"><div class="filter-row"><button class="filter active" data-filter="all">Tümü</button><?php foreach($categories as $category): ?><button class="filter" data-filter="<?=e($category)?>"><?=e($category)?></button><?php endforeach; ?></div><div class="blog-grid" id="blog-grid"><?php foreach($posts as $i=>$post): ?><a class="blog-card" data-category="<?=e($post['category'])?>" href="/blog/<?=e($post['slug'])?>/"><div class="card-cover <?=e(categoryClass($post['category']))?>"><span class="card-category"><?=e($post['category'])?></span><span class="card-index"><?=str_pad((string)($i+1),2,'0',STR_PAD_LEFT)?></span></div><div class="card-body"><span class="card-meta"><?=e(trDate($post['date']))?> · <?=e($post['readingMinutes'])?> dk</span><h2><?=e($post['title'])?></h2><p><?=e($post['excerpt'])?></p><span class="card-more">Yazıyı Oku →</span></div></a><?php endforeach; ?></div></div></section></main>
<footer class="site-footer"><div class="wrap"><div class="footer-grid"><div><img src="/assets/logo-fixed.webp" alt="Vensis"><p>Fan, havalandırma ve endüstriyel elektrik çözümleri.</p></div><div><h4>İçerikler</h4><a href="/blog/">Tüm Yazılar</a><a href="/blog/#ex-proof">Ex-Proof</a><a href="/blog/#fan-teknolojileri">Fan Teknolojileri</a></div><div><h4>İletişim</h4><a href="tel:+903129451360">0312 945 13 60</a><a href="mailto:vensis@vensis.com.tr">vensis@vensis.com.tr</a></div></div><div class="copy"><span>© <?=date('Y')?> Vensis Havalandırma Ltd. Şti.</span><span>Ankara, Türkiye</span></div></div></footer>
<script>document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(item=>item.classList.remove('active'));button.classList.add('active');document.querySelectorAll('.blog-card').forEach(card=>card.hidden=button.dataset.filter!=='all'&&card.dataset.category!==button.dataset.filter)}));</script></body></html>
