<?php
$posts = json_decode(file_get_contents(__DIR__.'/../data/blog-posts.json'), true) ?: [];
$slug = $slug ?? '';
$post = null;
foreach($posts as $item){ if($item['slug']===$slug){ $post=$item; break; } }
if(!$post){ http_response_code(404); $post=['title'=>'Yazı bulunamadı','date'=>date('Y-m-d'),'category'=>'Blog','readingMinutes'=>1,'excerpt'=>'Aradığınız yazı bulunamadı.','content'=>'<p>Blog arşivine dönerek diğer yazıları inceleyebilirsiniz.</p>','sources'=>[],'slug'=>'']; }
function e($value){ return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function trDate($date){ $m=['01'=>'Ocak','02'=>'Şubat','03'=>'Mart','04'=>'Nisan','05'=>'Mayıs','06'=>'Haziran','07'=>'Temmuz','08'=>'Ağustos','09'=>'Eylül','10'=>'Ekim','11'=>'Kasım','12'=>'Aralık']; [$y,$mo,$d]=explode('-',$date); return (int)$d.' '.$m[$mo].' '.$y; }
?><!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($post['title'])?> | Vensis</title><meta name="description" content="<?=e($post['excerpt'])?>"><link rel="canonical" href="https://vensis.com.tr/blog/<?=e($post['slug'])?>/"><link rel="stylesheet" href="/assets/blog.css?v=20260721-1"><link rel="icon" type="image/webp" href="/assets/logo-fixed.webp"></head><body>
<div class="site-top"><div class="wrap"><span>Vensis Havalandırma Ltd. Şti.</span><span>0312 945 13 60 · vensis@vensis.com.tr</span></div></div><header class="site-header"><div class="wrap site-nav"><a class="site-logo" href="/"><img src="/assets/logo-fixed.webp" alt="Vensis"></a><nav class="site-menu"><a href="/">Ana Sayfa</a><a href="/#cozumler">Çözümler</a><a href="/#referanslar">Referanslar</a><a class="active" href="/blog/">Blog</a><a href="/#iletisim">İletişim</a></nav><a class="site-btn" href="/#iletisim">Projenizi Konuşalım</a></div></header>
<main><section class="article-hero"><div class="wrap"><div class="article-meta"><b><?=e($post['category'])?></b><span><?=e(trDate($post['date']))?></span><span><?=e($post['readingMinutes'])?> dakika okuma</span></div><h1><?=e($post['title'])?></h1></div></section><div class="wrap article-layout"><article class="article-content"><?=$post['content']?><a class="back-link" href="/blog/">← Tüm yazılara dön</a></article><aside class="article-side"><div class="side-box"><h3>Projeniz için doğru ürünü seçelim.</h3><p>Teknik ihtiyacınızı paylaşın; fan, elektrik ve ex-proof çözümler için size dönüş yapalım.</p><a class="site-btn" href="/#iletisim">İletişime Geç</a></div><?php if($post['sources']): ?><div class="source-box"><b>İlk yayınlandığı uzmanlık siteleri</b><?php foreach($post['sources'] as $source): ?><a href="<?=e($source['url'])?>" target="_blank" rel="noopener"><?=e($source['name'])?> ↗</a><?php endforeach; ?></div><?php endif; ?></aside></div></main>
<footer class="site-footer"><div class="wrap"><div class="footer-grid"><div><img src="/assets/logo-fixed.webp" alt="Vensis"><p>Fan, havalandırma ve endüstriyel elektrik çözümleri.</p></div><div><h4>Blog</h4><a href="/blog/">Tüm Yazılar</a><a href="/">Ana Sayfa</a></div><div><h4>İletişim</h4><a href="tel:+903129451360">0312 945 13 60</a><a href="mailto:vensis@vensis.com.tr">vensis@vensis.com.tr</a></div></div><div class="copy"><span>© <?=date('Y')?> Vensis Havalandırma Ltd. Şti.</span><span>Ankara, Türkiye</span></div></div></footer></body></html>
